import { Job, Skill } from "./types";

export const skillList: Record<Job, Skill[]> = {
  "Software Developer": [
    {
      title: "HTML",
      percentage: 95,
      icon: "https://cdn.worldvectorlogo.com/logos/html-1.svg",
      color: "#E44D26",
    },
    {
      title: "CSS",
      percentage: 95,
      icon: "https://cdn.worldvectorlogo.com/logos/css-3.svg",
      color: "#1B73BA",
    },
    {
      title: "JS",
      percentage: 90,
      icon: "https://cdn.worldvectorlogo.com/logos/javascript-1.svg",
      color: "#F7DF1E",
    },
    {
      title: "TS",
      percentage: 90,
      icon: "https://cdn.worldvectorlogo.com/logos/typescript.svg",
      color: "#007ACC",
    },
    {
      title: "React Js",
      percentage: 95,
      icon: "https://cdn.worldvectorlogo.com/logos/react-2.svg",
      color: "#61DAFB",
    },
    {
      title: "Next Js",
      percentage: 90,
      icon: "https://cdn.worldvectorlogo.com/logos/next-js.svg",
      color: "#FF3684",
      iconBorder: true,
    },
    {
      title: "Vue Js",
      percentage: 15,
      icon: "https://cdn.worldvectorlogo.com/logos/vue-9.svg",
      color: "#41B883",
    },
    {
      title: "React Native",
      percentage: 50,
      icon: "https://cdn.worldvectorlogo.com/logos/react-native-1.svg",
      color: "#61DAFB",
    },
    {
      title: "Node",
      percentage: 95,
      icon: "https://cdn.worldvectorlogo.com/logos/nodejs-icon.svg",
      color: "#8CC84B",
    },
    {
      title: "Express",
      percentage: 95,
      icon: "https://cdn.worldvectorlogo.com/logos/express-109.svg",
      color: "#FF3684",
      iconBorder: true,
    },
    {
      title: "Nest JS",
      percentage: 90,
      icon: "https://icon.icepanel.io/Technology/svg/Nest.js.svg",
      color: "#DF234F",
    },
    {
      title: "PHP",
      percentage: 85,
      icon: "https://icon.icepanel.io/Technology/svg/PHP.svg",
      color: "#777BB3",
    },
    {
      title: "Laravel",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/svg/Laravel.svg",
      color: "#F05340",
    },
    {
      title: "Symfony",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/png-shadow-512/Symfony.png",
      color: "#FF3684",
      iconBorder: true,
    },
    {
      title: "SQL",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/svg/PostgresSQL.svg",
      color: "#336791",
    },
    {
      title: "MongoDB",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/svg/MongoDB.svg",
      color: "#439934",
    },
    {
      title: "AWS",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/png-shadow-512/AWS.png",
      color: "#FFB139",
      iconBorder: true,
    },
    {
      title: "GCP",
      percentage: 60,
      icon: "https://icon.icepanel.io/Technology/svg/Google-Cloud.svg",
      color: "#36A852",
    },
    {
      title: "C",
      percentage: 50,
      icon: "https://icon.icepanel.io/Technology/svg/C.svg",
      color: "#03599C",
    },
    {
      title: "Java",
      percentage: 75,
      icon: "https://icon.icepanel.io/Technology/svg/Java.svg",
      color: "#EA2D2E",
    },
    {
      title: "Python",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/svg/Python.svg",
      color: "#FFDD53",
    },
    {
      title: "Django",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/png-shadow-512/Django.png",
      color: "#072E1F",
      iconBorder: true,
    },
    {
      title: "GraphQL",
      percentage: 90,
      icon: "https://icon.icepanel.io/Technology/svg/GraphQL.svg",
      color: "#E434AA",
    },
    {
      title: "Docker",
      percentage: 80,
      icon: "https://icon.icepanel.io/Technology/svg/Docker.svg",
      color: "#028BB8",
    },
  ],
  "UI/UX Designer": [
    {
      title: "Figma",
      percentage: 90,
      icon: "https://icon.icepanel.io/Technology/svg/Figma.svg",
      color: "#A259FF",
    },
    {
      title: "Adobe XD",
      percentage: 50,
      icon: "https://icon.icepanel.io/Technology/svg/Adobe-XD.svg",
      color: "#DD80BC",
    },
    {
      title: "Adobe Photoshop",
      percentage: 50,
      icon: "https://icon.icepanel.io/Technology/svg/Adobe-Photoshop.svg",
      color: "#80B5E2",
    },
    {
      title: "Adobe Illustrator",
      percentage: 50,
      icon: "https://icon.icepanel.io/Technology/svg/Adobe-Illustrator.svg",
      color: "#FAA625",
    },
    {
      title: "Filmora",
      percentage: 80,
      icon: "https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/filmora-logo-icon.png",
      color: "#1A394E",
    },
    {
      title: "Adobe Premier Pro",
      percentage: 50,
      icon: "https://icon.icepanel.io/Technology/svg/Adobe-Premiere-Pro.svg",
      color: "#2A0634",
    },
  ],
  "Digital Marketer": [
    {
      title: "Wordpress",
      percentage: 70,
      icon: "https://cdn.worldvectorlogo.com/logos/wordpress-icon-1.svg",
      color: "#21759B",
    },
    {
      title: "SEO",
      percentage: 80,
      icon: "https://www.svgrepo.com/show/388528/seo.svg",
      color: "#2F88FF",
    },
    {
      title: "SEM",
      percentage: 80,
      icon: "https://www.svgrepo.com/show/390230/search-ranking-analytics.svg",
      color: "#FF3684",
      iconBorder: true,
    },
    {
      title: "Google Adsense",
      percentage: 70,
      icon: "https://cdn.worldvectorlogo.com/logos/google-adsense.svg",
      color: "#E44D26",
    },
    {
      title: "Google Adwords",
      percentage: 90,
      icon: "https://cdn.worldvectorlogo.com/logos/google-adwords-1.svg",
      color: "#F4B810",
    },
    {
      title: "Google Ananlytics",
      percentage: 80,
      icon: "https://cdn.worldvectorlogo.com/logos/google-analytics-4.svg",
      color: "#E37400",
    },
    {
      title: "Facebook Marketing",
      percentage: 80,
      icon: "https://cdn.worldvectorlogo.com/logos/facebook-3-2.svg",
      color: "#3C5A9A",
    },
    {
      title: "Instagram Marketing",
      percentage: 80,
      icon: "https://cdn.worldvectorlogo.com/logos/instagram-2016-5.svg",
      color: "#E34C60",
    },
    {
      title: "Youtube Marketing",
      percentage: 90,
      icon: "https://cdn.worldvectorlogo.com/logos/youtube-icon-5.svg",
      color: "#CD201F",
    },
    {
      title: "Mailchimp",
      percentage: 80,
      icon: "https://cdn.worldvectorlogo.com/logos/mailchimp-freddie-icon.svg",
      color: "#3387C4",
    },
    {
      title: "Affiliate Marketing",
      percentage: 60,
      icon: "https://cdn.worldvectorlogo.com/logos/google-marketing-platform.svg",
      color: "#34A853",
    },
  ],
};
